name=CallbackTimer
version=1.0.0
author=Leeor Nahum <leeornahum@gmail.com>
maintainer=Leeor Nahum <leeornahum@gmail.com>
sentence=Library for creating timers with callbacks in Arduino sketches.
paragraph=The CallbackTimer library provides a simple way to create timers in Arduino sketches. It allows you to specify an amount of time and a callback function that will be executed when the time has expired. The library also provides methods for enabling and disabling the timer, as well as getting and setting the time.
category=Timing
url=https://www.google.com/
architectures=*
includes=CallbackTimer.h